/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/CloudyNight.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CloudyNightModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/CloudyNight.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials["material_1.001"]}
      />
    </group>
  );
}

useGLTF.preload("/CloudyNight.glb");
