/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/HeavySnow.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HeavySnowModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/HeavySnow.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.141}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials["material.001"]}
            position={[-0.006, -0.001, -0.019]}
            scale={[0.145, 0.099, 0.073]}
          />
          <mesh
            geometry={nodes.Object_89.geometry}
            material={materials["material_19.001"]}
            position={[0.025, -0.064, 0.002]}
            scale={0.003}
          />
          <mesh
            geometry={nodes.Object_91.geometry}
            material={materials["material_19.001"]}
            position={[-0.028, -0.065, 0.002]}
            scale={0.003}
          />
          <mesh
            geometry={nodes.Object_93.geometry}
            material={materials["material_19.001"]}
            position={[-0.003, -0.025, 0.002]}
            scale={0.003}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/HeavySnow.glb");
