/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/LightSnow.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LightSnowModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/LightSnow.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials["material.001"]}
        position={[-0.001, 0.003, 0.001]}
        scale={[0.145, 0.099, 0.073]}
      />
      <mesh
        geometry={nodes.Object_95.geometry}
        material={materials["material_19.001"]}
        position={[-0.001, -0.065, 0.022]}
        scale={0.003}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/LightSnow.glb");
