/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/Night.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function NightModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/Night.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["material_1.001"]}
        position={[0.001, 0.005, 0.001]}
        scale={[0.086, 0.101, 0.009]}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/Night.glb");
