/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function PartlyCloudyModel(props) {
  const group = useRef();
  const rays = useRef();
  const { nodes, materials } = useGLTF("/assets/models/PartlyCloudy5.glb");

  useFrame((state) => {
    const t = state.clock.getElapsedTime();

    // Floating cloud animation
    group.current.position.y = Math.sin(t * 1.5) * 0.2;
    group.current.rotation.y = Math.sin(t * 0.8) * 0.1;
    group.current.rotation.z = Math.cos(t * 0.5) * 0.05;

    // Sun rays animation (gentle rotation and pulsing)
    if (rays.current) {
      rays.current.rotation.z = Math.sin(t) * 0.15; // slight back-and-forth rotation
      const pulse = 1 + Math.sin(t * 3) * 0.05; // subtle scaling
      rays.current.scale.set(pulse, pulse, pulse);
    }
  });

  return (
    <group ref={group} scale={15} {...props} dispose={null}>
      {/* Main cloud & sun body */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials["material_8.002"]}
      />

      {/* Group for rays so they can move together */}
      <group ref={rays}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials["material_10.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials["material_11.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials["material_12.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials["material_13.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials["material_14.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials["material_15.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials["material_16.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials["material_17.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials["material_13.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/PartlyCloudy5.glb");
