/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/Sleet.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SleetModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/Sleet.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <mesh geometry={nodes.Object_31.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Object_109.geometry}
        material={materials.material_20}
      />
      <mesh
        geometry={nodes.Object_111.geometry}
        material={materials.material_19}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/Sleet.glb");
