/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/Snow.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SnowModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/Snow.glb");
  return (
    <group scale={40} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["material.001"]}
        position={[-0.001, 0.002, -0.002]}
        scale={[0.145, 0.099, 0.073]}
      />
      <mesh
        geometry={nodes.Object_85.geometry}
        material={materials["material_19.001"]}
        position={[0.028, -0.06, 0.02]}
        scale={0.003}
      />
      <mesh
        geometry={nodes.Object_87.geometry}
        material={materials["material_19.001"]}
        position={[-0.025, -0.06, 0.02]}
        scale={0.003}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/Snow.glb");
