/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function SunnyModel(props) {
  const group = useRef();
  const rays = useRef();
  const { nodes, materials } = useGLTF("/assets/models/Sunny.glb");

  useFrame((state) => {
    const t = state.clock.getElapsedTime();

    // Gentle floating (same feel as PartlyCloudyModel)
    if (group.current) {
      group.current.position.y = Math.sin(t * 1.5) * 0.2;
      group.current.rotation.y = Math.sin(t * 0.8) * 0.1;
      group.current.rotation.z = Math.cos(t * 0.5) * 0.05;
    }

    // Sun rays: slight oscillating rotation + subtle pulse
    if (rays.current) {
      rays.current.rotation.z = Math.sin(t) * 0.15;
      const pulse = 1 + Math.sin(t * 3) * 0.05;
      rays.current.scale.set(pulse, pulse, pulse);
    }
  });

  return (
    <group ref={group} scale={20} {...props} dispose={null}>
      {/* Sun core */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_67.geometry}
        material={materials.material_18}
        position={[-0.007, 0, -0.017]}
      />

      {/* Rays grouped so they animate together */}
      <group ref={rays}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials.material_13}
          position={[0.078, 0.076, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.material_13}
          position={[0.106, -0.001, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.material_13}
          position={[0.076, -0.075, -0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_75.geometry}
          material={materials.material_13}
          position={[-0.005, -0.114, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_77.geometry}
          material={materials.material_13}
          position={[-0.09, -0.074, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.material_13}
          position={[-0.117, -0.003, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_81.geometry}
          material={materials.material_13}
          position={[-0.088, 0.075, -0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_83.geometry}
          material={materials.material_13}
          position={[-0.007, 0.109, -0.01]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Sunny.glb");
